# Generated by Django 5.0.3 on 2024-03-16 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=250, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('sort', models.IntegerField(blank=True, default=0, null=True, verbose_name='Sort')),
                ('temperature_from', models.FloatField(blank=True, help_text='in ° C', null=True, verbose_name='Temperature_from')),
                ('temperature_to', models.FloatField(blank=True, help_text='in ° C', null=True, verbose_name='Temperature_to')),
            ],
            options={
                'verbose_name': 'wine',
                'verbose_name_plural': 'wine-plural',
                'ordering': ('sort',),
            },
        ),
        migrations.CreateModel(
            name='Winery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=250, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('sort', models.IntegerField(blank=True, default=0, null=True, verbose_name='Sort')),
            ],
            options={
                'verbose_name': 'Winery',
                'verbose_name_plural': 'Winery-plural',
                'ordering': ('sort',),
            },
        ),
        migrations.CreateModel(
            name='Vintage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0, verbose_name='Year')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vintages', to='main.wine')),
            ],
        ),
        migrations.AddField(
            model_name='wine',
            name='winery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wines', to='main.winery'),
        ),
    ]
