# Generated by Django 5.0.3 on 2024-03-17 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='wine',
            name='description_sk',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
