# Generated by Django 4.0b1 on 2021-11-15 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tof', '0003_create_field_for_static'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translatablefield',
            name='title',
        ),
    ]
