# Generated by Django 4.0.2 on 2022-05-14 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tof', '0004_remove_translatablefield_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('app_label', 'tof'), _negated=True), on_delete=django.db.models.deletion.DO_NOTHING, related_name='translations', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='translations', to='tof.translatablefield'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='lang',
            field=models.ForeignKey(limit_choices_to=models.Q(('is_active', True)), on_delete=django.db.models.deletion.DO_NOTHING, related_name='translations', to='tof.language'),
        ),
    ]
